add handling multiple versions of OL and components
Signed-off-by: tnazarew <tomasz.nazarewicz@getindata.com>

diff --git a/.github/workflows/main_pr.yml b/.github/workflows/main_pr.yml
--- a/.github/workflows/main_pr.yml
+++ b/.github/workflows/main_pr.yml
@@ -20,6 +20,7 @@ jobs:
       run_spark_dataproc: ${{ steps.get-changed.outputs.spark_dataproc_changed }}
       ol_release: ${{ steps.get-release.outputs.openlineage_release }}
       any_run: ${{ steps.get-changed.outputs.any_changed }}
+      test_matrix: ${{ steps.set-matrix-values.outputs.spark_dataproc_matrix }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -64,7 +65,24 @@ jobs:
         run: |
           echo " any changed value is ${{ steps.get-changed.outputs.any_changed }}"
           openlineage_release=$(cat generated-files/releases.json | jq -c '.[] | select(.name | contains("openlineage")) | .latest_version ' -r)
-          echo "openlineage_release=${openlineage_release}" >> $GITHUB_OUTPUT  
+          echo "openlineage_release=${openlineage_release}" >> $GITHUB_OUTPUT
+      - name: set-matrix-values
+        id: set-matrix-values
+        run: |
+          check_producer() {
+              local producer="$1"
+              local file="./producer/${producer}/versions.json"
+
+              if [[ -f "$file" ]]; then
+                  cat "$file" | jq -c
+              else
+                  echo "Error: File '$file' does not exist." >&2
+                  return 1
+              fi
+          }
+          echo "spark_dataproc_matrix=$(check_producer spark_dataproc)" >> $GITHUB_OUTPUT
+
+          # echo "myoutput=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT
 
   ######## COMPONENT VALIDATION ########
 
@@ -87,17 +105,20 @@ jobs:
     with:
       release: ${{ needs.initialize_workflow.outputs.ol_release }}
 
-  spark_dataproc:
-    needs: initialize_workflow
-    if: ${{ needs.initialize_workflow.outputs.run_spark_dataproc == 'true' }}
-    uses: ./.github/workflows/producer_spark_dataproc.yml
-    secrets:
-      gcpKey: ${{ secrets.GCP_SA_KEY }}
-      postgresqlUser: ${{ secrets.POSTGRESQL_USER }}
-      postgresqlPassword: ${{ secrets.POSTGRESQL_PASSWORD }}
-    with:
-      release: ${{ needs.initialize_workflow.outputs.ol_release }}
-      get-latest-snapshots: 'false'
+#  spark_dataproc:
+#    needs: initialize_workflow
+#    if: ${{ needs.initialize_workflow.outputs.run_spark_dataproc == 'true' }}
+#    uses: ./.github/workflows/producer_spark_dataproc.yml
+#    strategy:
+#      matrix: ${{ fromJson(needs.initialize_workflow.outputs.test_matrix) }}
+#    secrets:
+#      gcpKey: ${{ secrets.GCP_SA_KEY }}
+#      postgresqlUser: ${{ secrets.POSTGRESQL_USER }}
+#      postgresqlPassword: ${{ secrets.POSTGRESQL_PASSWORD }}
+#    with:
+#      ol_release: ${{ matrix.openlineage_versions }}
+#      spark_release: ${{ matrix.component_version }}
+#      get-latest-snapshots: 'false'
 
   ######## COLLECTION OF REPORTS AND EXECUTE APPROPRIATE ACTIONS ########
 
@@ -106,7 +127,7 @@ jobs:
       - initialize_workflow
       - scenarios
       - dataplex
-      - spark_dataproc
+#      - spark_dataproc
     if: ${{ !failure() && needs.initialize_workflow.outputs.any_run  == 'true'}}
     uses: ./.github/workflows/collect_and_compare_reports.yml
     with:
